FORMAT: 1A

# TouchPoint History Data Capture API

Service for touchpoint history. (https://www.bcbsnc.com/members)

## Status [/members/services/sec/touchpoints]

### Send data capture details [POST]

+ Request (application/json)

  + Headers

            Accept: application/json

  + Body

            {

            }

+ Response 200 (application/json)

  + Headers

            Accept: application/json

  + Body

            {

            }

+ Response 401 (application/json)

  + Headers

            Accept: application/json

  + Body

            {

            }
